/** Built-in, read-only Cisco IOS lab recipes. User-created commands stay in the repository. */
export type LibrarySection = { title: string; explanation: string; code: string };
export type VerifyCommand = { command: string; meaning: string };
export type LibraryArticle = {
  id: string; title: string; category: string; description: string; tags: string[];
  kind: 'topic' | 'full'; devices: { name: string; sections: LibrarySection[] }[];
  topology?: string; lab?: string[]; variables?: Record<string, string>;
  preparation?: LibrarySection[];
  verify: VerifyCommand[]; issues: { symptom: string; checks: string[] }[];
  caution?: string;
};

export const libraryCategories = ['CƠ BẢN', 'SWITCH LAYER 2', 'SWITCH LAYER 3', 'ROUTER CISCO', 'REDUNDANCY / HIGH AVAILABILITY', 'SWITCHING', 'ROUTING', 'SECURITY', 'TROUBLESHOOTING / SHOW COMMAND', 'FULL CONFIG'] as const;

const s = (title: string, explanation: string, code: string): LibrarySection => ({ title, explanation, code });
const v = (command: string, meaning: string): VerifyCommand => ({ command, meaning });
const issue = (symptom: string, ...checks: string[]) => ({ symptom, checks });
const save = s('Lưu cấu hình', 'Ghi running-config vào NVRAM.', 'end\ncopy running-config startup-config');
const vlanVerify = [v('show vlan brief', 'Xem VLAN và port access.'), v('show interfaces trunk', 'Xem trunk và VLAN được phép.')];
const routeVerify = [v('show ip interface brief', 'Xem IP và trạng thái interface.'), v('show ip route', 'Xem bảng định tuyến.')];
const lacpVerify = [v('show etherchannel summary', 'Kiểm tra port-channel đã bundle.'), v('show interfaces trunk', 'Kiểm tra VLAN trên port-channel.')];
const hsrpVerify = [v('show standby brief', 'Xem Active/Standby và VIP.'), v('show track', 'Xem trạng thái đối tượng theo dõi.')];
const vlanIssue = issue('VLAN không thông hoặc PC không nhận DHCP', 'Kiểm tra port access đúng VLAN.', 'Kiểm tra trunk cho phép VLAN.', 'Kiểm tra gateway và DHCP pool.');
const lacpIssue = issue('Port-channel không lên', 'Hai đầu phải có cùng mode trunk/access và allowed VLAN.', 'Kiểm tra speed, duplex và mode active/passive.', 'Chạy show etherchannel summary.');
const hsrpIssue = issue('Mất WAN nhưng gateway chưa chuyển', 'Kiểm tra track và priority decrement.', 'Bật preempt ở router dự phòng.', 'Chạy show track và show standby brief.');

const topics: LibraryArticle[] = [];
function topic(category: string, title: string, code: string, explanation: string, verify: VerifyCommand[], tags: string[] = [], issues = [issue('Lệnh chưa có hiệu lực', 'Kiểm tra đúng chế độ cấu hình và đúng interface.', 'Chạy lệnh show tương ứng để xác nhận.')], caution?: string) {
  topics.push({ id: `topic-${title.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/đ/g, 'd').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}-${topics.length}`, title, category, description: explanation, tags: ['Cisco', 'CCNA', ...tags], kind: 'topic', devices: [{ name: 'Cisco IOS', sections: [s(title, explanation, code)] }], verify, issues, caution });
}

// Each topic is a short, copyable IOS command recipe, with the relevant show command.
topic('CƠ BẢN', 'Reset / xóa cấu hình Cisco', 'enable\nwrite erase\ndelete flash:vlan.dat\nreload', 'Xóa startup-config; vlan.dat chỉ áp dụng switch có tệp này. Thực hiện từng lệnh và xác nhận tại thiết bị.', [v('show startup-config', 'Kiểm tra cấu hình lưu trước khi xóa.')], ['Reset'], [issue('Không tìm thấy vlan.dat', 'Bỏ qua bước xóa vlan.dat trên router hoặc switch không có tệp.')], 'Thao tác phá hủy cấu hình và gây gián đoạn. Sao lưu trước khi chạy; không dán cả khối vào thiết bị đang hoạt động.');
topic('CƠ BẢN', 'Enable / Configure Terminal', 'enable\nconfigure terminal', 'Vào privileged EXEC rồi global configuration.', [v('show running-config', 'Xác nhận cấu hình hiện tại.')]);
topic('CƠ BẢN', 'Hostname', 'configure terminal\nhostname SW1', 'Đặt tên thiết bị; đổi SW1 theo lab.', [v('show running-config | include hostname', 'Xem hostname.')]);
topic('CƠ BẢN', 'Enable Secret', 'configure terminal\nenable secret {{ENABLE_SECRET}}', 'Đặt mật khẩu cho privileged EXEC.', [v('show running-config | include enable secret', 'Xác nhận secret đã được lưu.')], ['Security'], undefined, 'Thay biến bằng secret riêng trước khi copy.');
topic('CƠ BẢN', 'Console Password', 'configure terminal\nline console 0\npassword {{CONSOLE_PASSWORD}}\nlogin', 'Yêu cầu mật khẩu ở console.', [v('show running-config | section line con', 'Xem cấu hình console.')], ['Security']);
topic('CƠ BẢN', 'Banner MOTD', 'configure terminal\nbanner motd #Authorized access only#', 'Thông báo khi đăng nhập; dấu # là delimiter.', [v('show running-config | include banner', 'Xem banner.')]);
topic('CƠ BẢN', 'Description interface', 'configure terminal\ninterface {{INTERFACE}}\ndescription UPLINK_TO_SW2', 'Gắn nhãn cổng theo sơ đồ.', [v('show interfaces description', 'Xem mô tả cổng.')], ['Interface']);
topic('CƠ BẢN', 'Shutdown / No shutdown', 'configure terminal\ninterface {{INTERFACE}}\nno shutdown', 'Bật interface; dùng shutdown khi cần tắt.', [v('show ip interface brief', 'Xem trạng thái cổng.')], ['Interface']);
topic('CƠ BẢN', 'Lưu cấu hình', 'end\ncopy running-config startup-config', 'Lưu thay đổi để không mất sau reload.', [v('show startup-config', 'Xem cấu hình đã lưu.')]);
topic('CƠ BẢN', 'Reload', 'enable\nreload', 'Khởi động lại thiết bị sau khi lưu cấu hình.', [v('show version', 'Xem thời gian uptime sau khởi động.')], [], undefined, 'Reload gây gián đoạn dịch vụ.');
topic('CƠ BẢN', 'SSH', 'configure terminal\nip domain-name lab.local\nusername admin privilege 15 secret {{ADMIN_SECRET}}\ncrypto key generate rsa modulus 2048\nip ssh version 2\nline vty 0 4\nlogin local\ntransport input ssh', 'Bật SSHv2 và xác thực tài khoản local.', [v('show ip ssh', 'Xem trạng thái SSH.'), v('show running-config | section line vty', 'Xem VTY.')], ['SSH', 'Security']);
topic('CƠ BẢN', 'Router Cisco cơ bản', 'enable\nconfigure terminal\nhostname R1\ninterface GigabitEthernet0/1\nip address 10.10.10.1 255.255.255.0\nno shutdown\nend\ncopy running-config startup-config', 'Khởi tạo router và một cổng LAN.', routeVerify, ['Router']);
topic('CƠ BẢN', 'Switch Layer 2 Cisco', 'enable\nconfigure terminal\nhostname SW1\nvlan 10\nname SALES\ninterface FastEthernet0/1\nswitchport mode access\nswitchport access vlan 10\nno shutdown\nend\ncopy running-config startup-config', 'Khởi tạo switch L2 và access port VLAN10.', vlanVerify, ['Switch L2', 'VLAN']);

topic('SWITCH LAYER 2', 'Tạo VLAN / Đặt tên VLAN', 'configure terminal\nvlan 10\nname SALES', 'Tạo VLAN 10 và tên SALES.', vlanVerify, ['VLAN'], [vlanIssue]);
topic('SWITCH LAYER 2', 'Access Port', 'configure terminal\ninterface {{ACCESS_PORT}}\nswitchport mode access\nswitchport access vlan 10\nno shutdown', 'Gán cổng người dùng vào VLAN 10.', vlanVerify, ['VLAN', 'Access'], [vlanIssue]);
topic('SWITCH LAYER 2', 'Trunk Port', 'configure terminal\ninterface {{TRUNK_PORT}}\nswitchport mode trunk\nswitchport trunk allowed vlan 10,20\nno shutdown', 'Cho VLAN 10,20 đi qua liên kết 802.1Q.', vlanVerify, ['VLAN', 'Trunk'], [vlanIssue]);
topic('SWITCH LAYER 2', 'Allowed VLAN', 'configure terminal\ninterface {{TRUNK_PORT}}\nswitchport trunk allowed vlan 10,20,30', 'Giới hạn VLAN qua trunk; lệnh này thay danh sách hiện có.', [v('show interfaces trunk', 'Xem allowed VLAN.')], ['Trunk', 'VLAN']);
topic('SWITCH LAYER 2', 'Native VLAN', 'configure terminal\ninterface {{TRUNK_PORT}}\nswitchport trunk native vlan 99', 'Hai đầu trunk phải dùng cùng native VLAN.', [v('show interfaces trunk', 'Xem native VLAN.')], ['Trunk', 'VLAN']);
topic('SWITCH LAYER 2', 'Voice VLAN', 'configure terminal\ninterface {{ACCESS_PORT}}\nswitchport mode access\nswitchport access vlan 10\nswitchport voice vlan 20', 'Data VLAN 10 và voice VLAN 20 trên cổng điện thoại IP.', vlanVerify, ['VLAN', 'Voice']);
topic('SWITCH LAYER 2', 'PortFast', 'configure terminal\ninterface {{ACCESS_PORT}}\nswitchport mode access\nspanning-tree portfast', 'Chỉ bật trên cổng nối thiết bị đầu cuối.', [v('show spanning-tree interface {{ACCESS_PORT}} detail', 'Xem trạng thái STP của cổng.')], ['STP']);
topic('SWITCH LAYER 2', 'BPDU Guard', 'configure terminal\ninterface {{ACCESS_PORT}}\nswitchport mode access\nspanning-tree portfast\nspanning-tree bpduguard enable', 'Chặn cổng edge khi nhận BPDU.', [v('show interfaces status', 'Tìm cổng err-disabled.')], ['STP', 'Security']);
topic('SWITCH LAYER 2', 'Port Security / Sticky MAC', 'configure terminal\ninterface {{ACCESS_PORT}}\nswitchport mode access\nswitchport port-security\nswitchport port-security maximum 2\nswitchport port-security mac-address sticky\nswitchport port-security violation restrict', 'Giới hạn hai MAC trên access port.', [v('show port-security interface {{ACCESS_PORT}}', 'Xem vi phạm và MAC học được.')], ['Security']);
topic('SWITCH LAYER 2', 'STP / Rapid-PVST', 'configure terminal\nspanning-tree mode rapid-pvst\nspanning-tree vlan 10,20 root primary', 'Bật Rapid-PVST và đặt switch làm root cho VLAN 10,20.', [v('show spanning-tree vlan 10', 'Xem root bridge và vai trò cổng.')], ['STP', 'Rapid-PVST']);
topic('SWITCH LAYER 2', 'Root Primary / Root Secondary', 'configure terminal\nspanning-tree vlan 10 root primary\nspanning-tree vlan 20 root secondary', 'Chỉ định vai trò root theo VLAN.', [v('show spanning-tree root', 'Xem root của từng VLAN.')], ['STP']);
topic('SWITCH LAYER 2', 'STP Priority', 'configure terminal\nspanning-tree vlan 10 priority 4096', 'Đặt bridge priority theo bội số 4096.', [v('show spanning-tree vlan 10', 'Xem bridge priority.')], ['STP']);
topic('SWITCH LAYER 2', 'STP Cost / Port Priority', 'configure terminal\ninterface {{TRUNK_PORT}}\nspanning-tree vlan 10 cost 10\nspanning-tree vlan 10 port-priority 64', 'Tinh chỉnh lựa chọn đường đi STP.', [v('show spanning-tree vlan 10', 'Xem cost và role.')], ['STP']);
topic('SWITCH LAYER 2', 'EtherChannel / LACP', 'configure terminal\ninterface range {{LACP_PORTS}}\nswitchport mode trunk\nchannel-group 1 mode active\nexit\ninterface port-channel 1\nswitchport mode trunk\nswitchport trunk allowed vlan 10,20', 'Gộp hai đường vật lý bằng LACP; cấu hình hai đầu tương ứng.', lacpVerify, ['LACP', 'EtherChannel', 'Trunk'], [lacpIssue]);
topic('SWITCH LAYER 2', 'PAgP', 'configure terminal\ninterface range {{LACP_PORTS}}\nswitchport mode trunk\nchannel-group 1 mode desirable', 'PAgP dành cho thiết bị Cisco hỗ trợ giao thức này.', lacpVerify, ['EtherChannel']);
topic('SWITCH LAYER 2', 'Management VLAN / Default Gateway', 'configure terminal\nvlan 99\nname MANAGEMENT\ninterface vlan 99\nip address 192.0.2.2 255.255.255.0\nno shutdown\nexit\nip default-gateway 192.0.2.1', 'SVI quản trị switch L2; gateway dùng khi switch không bật ip routing.', [v('show ip interface brief', 'Xem SVI quản trị.'), v('show running-config | include default-gateway', 'Xem gateway.')], ['Management', 'VLAN']);

topic('SWITCH LAYER 3', 'SVI / Inter-VLAN Routing', 'configure terminal\nip routing\nvlan 10\nvlan 20\ninterface vlan 10\nip address 10.10.10.1 255.255.255.0\nno shutdown\ninterface vlan 20\nip address 10.10.20.1 255.255.255.0\nno shutdown', 'SVI làm gateway cho từng VLAN trên switch L3.', routeVerify, ['SVI', 'VLAN', 'Inter-VLAN']);
topic('SWITCH LAYER 3', 'Routed Port / no switchport', 'configure terminal\nip routing\ninterface {{ROUTED_PORT}}\nno switchport\nip address 192.0.2.2 255.255.255.252\nno shutdown', 'Chuyển cổng switch L3 sang cổng định tuyến.', routeVerify, ['Routed Port']);
topic('SWITCH LAYER 3', 'DHCP / Excluded Address', 'configure terminal\nip dhcp excluded-address 10.10.10.1 10.10.10.20\nip dhcp pool VLAN10\nnetwork 10.10.10.0 255.255.255.0\ndefault-router 10.10.10.1\ndns-server 1.1.1.1', 'Cấp IP cho VLAN 10, chừa dải địa chỉ tĩnh.', [v('show ip dhcp binding', 'Xem lease đã cấp.')], ['DHCP']);
topic('SWITCH LAYER 3', 'Static Route / Default Route', 'configure terminal\nip routing\nip route 198.51.100.0 255.255.255.0 192.0.2.1\nip route 0.0.0.0 0.0.0.0 192.0.2.1', 'Định tuyến tới mạng đích và đường mặc định.', routeVerify, ['Routing']);
topic('SWITCH LAYER 3', 'OSPF trên Switch L3', 'configure terminal\nip routing\nrouter ospf 1\nnetwork 10.10.10.0 0.0.0.255 area 0\nnetwork 192.0.2.0 0.0.0.3 area 0', 'Quảng bá các mạng L3 vào OSPF area 0.', [v('show ip ospf neighbor', 'Xem láng giềng OSPF.'), ...routeVerify], ['OSPF']);
topic('SWITCH LAYER 3', 'EtherChannel Layer 3', 'configure terminal\nip routing\ninterface range {{LACP_PORTS}}\nno switchport\nchannel-group 1 mode active\nexit\ninterface port-channel 1\nno switchport\nip address 192.0.2.1 255.255.255.252\nno shutdown', 'Gộp cổng routed bằng LACP; đầu kia dùng IP 192.0.2.2/30.', [...lacpVerify, ...routeVerify], ['LACP', 'EtherChannel']);
topic('SWITCH LAYER 3', 'HSRP trên L3 Switch', 'configure terminal\ninterface vlan 10\nip address 10.10.10.2 255.255.255.0\nstandby 10 ip 10.10.10.1\nstandby 10 priority 110\nstandby 10 preempt', 'SVI dự phòng gateway 10.10.10.1.', hsrpVerify, ['HSRP']);
topic('SWITCH LAYER 3', 'Switch Layer 3 Cisco', 'enable\nconfigure terminal\nhostname SW-L3\nip routing\nvlan 10\ninterface vlan 10\nip address 10.10.10.1 255.255.255.0\nno shutdown\nend\ncopy running-config startup-config', 'Khởi tạo switch L3 và SVI gateway VLAN10.', routeVerify, ['Switch L3', 'SVI']);

topic('ROUTER CISCO', 'Cấu hình interface Router', 'configure terminal\ninterface {{LAN_PORT}}\ndescription LAN\nip address 10.10.10.1 255.255.255.0\nno shutdown', 'Đặt địa chỉ và bật cổng LAN.', routeVerify, ['Interface']);
topic('ROUTER CISCO', 'Router-on-a-Stick / dot1Q', 'configure terminal\ninterface {{TRUNK_PORT}}\nno ip address\nno shutdown\ninterface {{TRUNK_PORT}}.10\nencapsulation dot1Q 10\nip address 10.10.10.1 255.255.255.0\ninterface {{TRUNK_PORT}}.20\nencapsulation dot1Q 20\nip address 10.10.20.1 255.255.255.0', 'Một cổng router phục vụ hai VLAN qua sub-interface.', routeVerify, ['VLAN', 'Trunk', 'Inter-VLAN']);
topic('ROUTER CISCO', 'DHCP Server Router', 'configure terminal\nip dhcp excluded-address 10.10.10.1 10.10.10.20\nip dhcp pool LAN10\nnetwork 10.10.10.0 255.255.255.0\ndefault-router 10.10.10.1\ndns-server 1.1.1.1', 'Router cấp địa chỉ trong mạng LAN10.', [v('show ip dhcp binding', 'Xem lease DHCP.')], ['DHCP']);
topic('ROUTER CISCO', 'Floating Static Route', 'configure terminal\nip route 0.0.0.0 0.0.0.0 192.0.2.1\nip route 0.0.0.0 0.0.0.0 198.51.100.1 200', 'Đường dự phòng có administrative distance lớn hơn.', routeVerify, ['Routing', 'Failover']);
topic('ROUTER CISCO', 'NAT / PAT', 'configure terminal\naccess-list 1 permit 10.10.10.0 0.0.0.255\ninterface {{LAN_PORT}}\nip nat inside\ninterface {{WAN_PORT}}\nip nat outside\nip nat inside source list 1 interface {{WAN_PORT}} overload', 'PAT nhiều địa chỉ LAN ra IP cổng WAN.', [v('show ip nat translations', 'Xem bản dịch NAT.'), v('show ip nat statistics', 'Xem thống kê NAT.')], ['NAT', 'PAT']);
topic('ROUTER CISCO', 'PPPoE Client', 'configure terminal\ninterface {{WAN_PORT}}\nno ip address\npppoe enable group global\npppoe-client dial-pool-number 1\nno shutdown\ninterface Dialer1\nip address negotiated\nencapsulation ppp\ndialer pool 1\nppp chap hostname {{PPPOE_USER}}\nppp chap password {{PPPOE_PASSWORD}}\nip route 0.0.0.0 0.0.0.0 Dialer1', 'Mẫu PPPoE client; nhập thông tin do ISP cung cấp.', [v('show pppoe session', 'Xem phiên PPPoE.'), v('show ip interface brief', 'Xem Dialer1.')], ['PPPoE'], undefined, 'Một số IOS/ISP yêu cầu PAP, MTU hoặc cấu hình riêng.');
topic('ROUTER CISCO', 'DNS Lookup', 'configure terminal\nip domain-lookup\nip name-server 1.1.1.1', 'Cho phép router phân giải DNS.', [v('show hosts', 'Xem DNS cache và name server.')], ['DNS']);
topic('ROUTER CISCO', 'Track Interface / IP SLA', 'configure terminal\nip sla 1\nicmp-echo 203.0.113.1 source-interface {{WAN_PORT}}\nfrequency 5\nexit\nip sla schedule 1 life forever start-time now\ntrack 1 ip sla 1 reachability', 'Theo dõi IP đầu xa thay vì chỉ link vật lý.', [v('show ip sla statistics', 'Xem kết quả probe.'), v('show track', 'Xem track object.')], ['IP SLA', 'Failover']);

topic('REDUNDANCY / HIGH AVAILABILITY', 'HSRP cơ bản / Priority / Preempt', 'configure terminal\ninterface {{LAN_PORT}}\nip address 10.10.10.2 255.255.255.0\nstandby 10 ip 10.10.10.1\nstandby 10 priority 110\nstandby 10 preempt', 'Gateway ảo 10.10.10.1; router đối tác dùng IP .3 và priority 100.', hsrpVerify, ['HSRP', 'Redundancy']);
topic('REDUNDANCY / HIGH AVAILABILITY', 'HSRP Track / WAN Failover', 'configure terminal\ntrack 1 interface {{WAN_PORT}} line-protocol\ninterface {{LAN_PORT}}\nstandby 10 ip 10.10.10.1\nstandby 10 priority 110\nstandby 10 preempt\nstandby 10 track 1 decrement 30', 'Khi WAN down, priority giảm từ 110 xuống 80 để router còn lại tiếp quản.', hsrpVerify, ['HSRP', 'Track', 'Failover'], [hsrpIssue]);
topic('REDUNDANCY / HIGH AVAILABILITY', 'HSRP nhiều VLAN / Active-Standby theo VLAN', 'configure terminal\ninterface {{TRUNK_PORT}}.10\nencapsulation dot1Q 10\nip address 10.10.10.2 255.255.255.0\nstandby 10 ip 10.10.10.1\nstandby 10 priority 110\nstandby 10 preempt\ninterface {{TRUNK_PORT}}.20\nencapsulation dot1Q 20\nip address 10.10.20.2 255.255.255.0\nstandby 20 ip 10.10.20.1\nstandby 20 priority 90\nstandby 20 preempt', 'R1 active VLAN10, R2 nên có priority cao hơn ở VLAN20.', hsrpVerify, ['HSRP', 'VLAN']);

topic('ROUTING', 'Connected Route', 'configure terminal\ninterface {{LAN_PORT}}\nip address 10.10.10.1 255.255.255.0\nno shutdown', 'Mạng xuất hiện dạng C khi interface up/up.', routeVerify, ['Routing']);
topic('ROUTING', 'Static Route / Default Route', 'configure terminal\nip route 10.20.0.0 255.255.0.0 192.0.2.2\nip route 0.0.0.0 0.0.0.0 192.0.2.1', 'Thay next-hop theo sơ đồ thực tế.', routeVerify, ['Routing']);
topic('ROUTING', 'OSPF', 'configure terminal\nrouter ospf 1\nrouter-id 1.1.1.1\nnetwork 10.10.10.0 0.0.0.255 area 0\nnetwork 192.0.2.0 0.0.0.3 area 0', 'Kích hoạt OSPF trên các interface thuộc hai mạng.', [v('show ip ospf neighbor', 'Xem adjacency.'), ...routeVerify], ['OSPF']);
topic('ROUTING', 'Administrative Distance', 'configure terminal\nip route 10.20.0.0 255.255.0.0 192.0.2.2 200', 'Tuyến tĩnh AD 200 chỉ được dùng khi tuyến ưu tiên mất.', routeVerify, ['Routing']);
topic('SECURITY', 'ACL Standard', 'configure terminal\nip access-list standard MGMT_ONLY\npermit 10.10.99.0 0.0.0.255\nexit\nline vty 0 4\naccess-class MGMT_ONLY in', 'Chỉ cho mạng quản trị truy cập VTY.', [v('show access-lists', 'Xem ACL và lượt match.')], ['ACL', 'SSH']);
topic('SECURITY', 'ACL Extended', 'configure terminal\nip access-list extended BLOCK_WEB\ndeny tcp 10.10.10.0 0.0.0.255 any eq 80\npermit ip any any\nexit\ninterface {{LAN_PORT}}\nip access-group BLOCK_WEB in', 'Chặn HTTP từ VLAN10 khi vào cổng LAN; vẫn cho lưu lượng khác.', [v('show access-lists', 'Xem số match.'), v('show ip interface {{LAN_PORT}}', 'Xem ACL gắn trên cổng.')], ['ACL']);

const showRows: [string, string][] = [
  ['show running-config','Xem cấu hình đang chạy.'],['show startup-config','Xem cấu hình đã lưu.'],['show ip interface brief','Xem IP và trạng thái interface.'],['show interfaces','Xem lỗi và counters cổng.'],['show interfaces status','Xem trạng thái switchport.'],['show interfaces trunk','Xem trunk và allowed VLAN.'],['show vlan brief','Xem VLAN và port.'],['show spanning-tree','Xem cây STP.'],['show spanning-tree vlan 10','Xem STP riêng VLAN 10.'],['show etherchannel summary','Xem trạng thái port-channel.'],['show interfaces port-channel 1','Xem chi tiết port-channel 1.'],['show mac address-table','Xem MAC đã học.'],['show arp','Xem ARP.'],['show ip route','Xem bảng định tuyến.'],['show ip protocols','Xem giao thức định tuyến.'],['show ip ospf neighbor','Xem láng giềng OSPF.'],['show standby brief','Xem HSRP Active/Standby.'],['show standby','Xem chi tiết HSRP.'],['show track','Xem track object.'],['show ip nat translations','Xem bản dịch NAT.'],['show access-lists','Xem ACL và số match.'],['show cdp neighbors','Xem hàng xóm CDP.'],['show cdp neighbors detail','Xem IP và cổng hàng xóm.'],['show version','Xem IOS, model và uptime.']
];
for (const [command, meaning] of showRows) topic('TROUBLESHOOTING / SHOW COMMAND', command, command, meaning, [v(command, meaning)], ['Show Commands', command.split(' ')[1] || '', ...(command.includes('etherchannel') || command.includes('port-channel') ? ['LACP', 'EtherChannel'] : []), ...(command.includes('standby') || command.includes('track') ? ['HSRP'] : []), ...(command.includes('trunk') ? ['Trunk'] : [])]);
topic('TROUBLESHOOTING / SHOW COMMAND', 'Show Commands', showRows.map(([command]) => command).join('\n'), 'Bảng lệnh kiểm tra nhanh sau cấu hình.', showRows.map(([command, meaning]) => v(command, meaning)), ['Troubleshooting']);

export const topicArticles = topics;

type DeviceRecipe = { name: string; sections: LibrarySection[] };
const fulls: LibraryArticle[] = [];
const defaults: Record<string, string> = {
  HOSTNAME: 'SW1', ACCESS_PORT: 'FastEthernet0/1', ACCESS_PORTS_10: 'FastEthernet0/1 - 5', ACCESS_PORTS_20: 'FastEthernet0/6 - 10',
  ACCESS_PORT_10: 'FastEthernet0/1', ACCESS_PORT_20: 'FastEthernet0/2', ACCESS_PORT_30: 'FastEthernet0/3', ACCESS_PORT_40: 'FastEthernet0/4',
  TRUNK_PORT: 'GigabitEthernet0/1', LACP_PORTS: 'GigabitEthernet0/1 - 2', ROUTED_PORT: 'GigabitEthernet0/2',
  TRUNK_PORT_1: 'GigabitEthernet0/1', TRUNK_PORT_2: 'GigabitEthernet0/2',
  LAN_PORT: 'GigabitEthernet0/1', WAN_PORT: 'GigabitEthernet0/0', SECOND_WAN_PORT: 'GigabitEthernet0/2',
  REMOTE_DEVICE: 'SW2', ALLOWED_VLANS: '10,20', VLAN_ID: '10', VLAN_NAME: 'SALES',
  MGMT_IP: '192.0.2.2', MGMT_GW: '192.0.2.1', MGMT_PORT: 'FastEthernet0/24', ADMIN_USER: 'admin', ADMIN_SECRET: 'CHANGE_ME_SECRET',
  ENABLE_SECRET: 'CHANGE_ME_ENABLE', PPPOE_USER: 'user@example.net', PPPOE_PASSWORD: 'CHANGE_ME_PPP',
};
const hostnameKey = (name: string) => `HOSTNAME_${name.toUpperCase().replace(/[^A-Z0-9]/g, '_')}`;
const starter = (hostname: string) => s('Basic Configuration', `Đặt hostname ${hostname}.`, `enable\nconfigure terminal\nhostname {{${hostnameKey(hostname)}}}`);
const l2Vlan = s('VLAN', 'Tạo VLAN 10 và 20; đổi ID/tên theo lab.', 'vlan 10\n name SALES\nexit\nvlan 20\n name ENGINEERING\nexit');
const l2Access = s('Access Port', 'Gán các cổng người dùng; PortFast/BPDU Guard chỉ dành cho thiết bị đầu cuối.', 'interface range {{ACCESS_PORTS_10}}\n switchport mode access\n switchport access vlan 10\n spanning-tree portfast\n spanning-tree bpduguard enable\n no shutdown\nexit\ninterface range {{ACCESS_PORTS_20}}\n switchport mode access\n switchport access vlan 20\n spanning-tree portfast\n spanning-tree bpduguard enable\n no shutdown\nexit');
const l2Trunk = s('Trunk', 'Trunk uplink, hai đầu thống nhất allowed VLAN và native VLAN.', 'interface {{TRUNK_PORT}}\n description TRUNK_TO_{{REMOTE_DEVICE}}\n switchport mode trunk\n switchport trunk allowed vlan {{ALLOWED_VLANS}}\n no shutdown\nexit');
const l2Stp = s('STP', 'Rapid-PVST và root VLAN 10,20 trên SW1.', 'spanning-tree mode rapid-pvst\nspanning-tree vlan 10,20 root primary');
const l2Lacp = s('LACP', 'Hai cổng vật lý cùng cấu hình; trunk được cấu hình trên Port-channel.', 'interface range {{LACP_PORTS}}\n switchport mode trunk\n channel-group 1 mode active\n no shutdown\nexit\ninterface port-channel 1\n description LACP_TO_{{REMOTE_DEVICE}}\n switchport mode trunk\n switchport trunk allowed vlan {{ALLOWED_VLANS}}\n no shutdown\nexit');
const l2LacpPeer = s('LACP', 'Đầu SW2 dùng cùng channel-group, allowed VLAN và cổng vật lý tương ứng.', l2Lacp.code.replace('{{REMOTE_DEVICE}}', 'SW1'));
const mgmt = s('Management', 'SVI quản trị switch L2; cổng quản trị phải kết nối để SVI lên.', 'vlan 99\n name MANAGEMENT\nexit\ninterface {{MGMT_PORT}}\n switchport mode access\n switchport access vlan 99\n no shutdown\nexit\ninterface vlan 99\n ip address {{MGMT_IP}} 255.255.255.0\n no shutdown\nexit\nip default-gateway {{MGMT_GW}}');
const l3Svi = s('SVI / Inter-VLAN Routing', 'Bật định tuyến và đặt gateway cho từng VLAN.', 'ip routing\nvlan 10\n name SALES\nexit\nvlan 20\n name ENGINEERING\nexit\ninterface vlan 10\n ip address 10.10.10.1 255.255.255.0\n no shutdown\nexit\ninterface vlan 20\n ip address 10.10.20.1 255.255.255.0\n no shutdown\nexit');
const l3Uplink = s('Routed Port / Default Route', 'Uplink routed tới router 192.0.2.1.', 'interface {{ROUTED_PORT}}\n no switchport\n ip address 192.0.2.2 255.255.255.252\n no shutdown\nexit\nip route 0.0.0.0 0.0.0.0 192.0.2.1');
const dhcp10 = s('DHCP', 'Loại trừ gateway và IP tĩnh; cấp IP cho VLAN10.', 'ip dhcp excluded-address 10.10.10.1 10.10.10.20\nip dhcp pool VLAN10\n network 10.10.10.0 255.255.255.0\n default-router 10.10.10.1\n dns-server 1.1.1.1\nexit');
const routerLan = s('LAN', 'Router làm gateway mạng 10.10.10.0/24.', 'interface {{LAN_PORT}}\n description LAN\n ip address 10.10.10.1 255.255.255.0\n no shutdown\nexit');
const routerWan = s('WAN / Default Route', 'Mạng /30 minh họa; đổi IP theo ISP.', 'interface {{WAN_PORT}}\n description TO_ISP\n ip address 192.0.2.2 255.255.255.252\n no shutdown\nexit\nip route 0.0.0.0 0.0.0.0 192.0.2.1');
const routerWan198 = s('WAN / Default Route', 'WAN dùng mạng khác liên kết R1–SW-L3.', 'interface {{WAN_PORT}}\n description TO_ISP\n ip address 198.51.100.2 255.255.255.252\n no shutdown\nexit\nip route 0.0.0.0 0.0.0.0 198.51.100.1');
const ros = s('Sub-interface / dot1Q', 'Cổng vật lý nối trunk switch; sub-interface làm gateway.', 'interface {{TRUNK_PORT}}\n no ip address\n no shutdown\nexit\ninterface {{TRUNK_PORT}}.10\n encapsulation dot1Q 10\n ip address 10.10.10.1 255.255.255.0\nexit\ninterface {{TRUNK_PORT}}.20\n encapsulation dot1Q 20\n ip address 10.10.20.1 255.255.255.0\nexit');
const nat = s('NAT / PAT', 'Đánh dấu inside/outside, overload ra IP WAN.', 'access-list 1 permit 10.10.10.0 0.0.0.255\ninterface {{LAN_PORT}}\n ip nat inside\nexit\ninterface {{WAN_PORT}}\n ip nat outside\nexit\nip nat inside source list 1 interface {{WAN_PORT}} overload');
const ospf = s('OSPF', 'Quảng bá LAN và liên kết WAN trong area 0.', 'router ospf 1\n router-id 1.1.1.1\n network 10.10.10.0 0.0.0.255 area 0\n network 192.0.2.0 0.0.0.3 area 0\nexit');
const hsrpR1 = s('HSRP', 'R1 ưu tiên Active; VIP .1 là gateway máy trạm.', 'interface {{LAN_PORT}}\n ip address 10.10.10.2 255.255.255.0\n standby 10 ip 10.10.10.1\n standby 10 priority 110\n standby 10 preempt\n no shutdown\nexit');
const hsrpR2 = s('HSRP', 'R2 dự phòng; preempt để chiếm quyền khi R1 mất WAN.', 'interface {{LAN_PORT}}\n ip address 10.10.10.3 255.255.255.0\n standby 10 ip 10.10.10.1\n standby 10 priority 100\n standby 10 preempt\n no shutdown\nexit');
const trackWan = s('Track WAN', 'Priority R1 giảm 30 khi WAN vật lý down.', 'track 1 interface {{WAN_PORT}} line-protocol\ninterface {{LAN_PORT}}\n standby 10 track 1 decrement 30\nexit');
const wan1 = s('WAN1 / Default Route', 'R1 ra ISP1.', 'interface {{WAN_PORT}}\n ip address 192.0.2.2 255.255.255.252\n no shutdown\nexit\nip route 0.0.0.0 0.0.0.0 192.0.2.1');
const wan2 = s('WAN2 / Default Route', 'R2 ra ISP2.', 'interface {{WAN_PORT}}\n ip address 198.51.100.2 255.255.255.252\n no shutdown\nexit\nip route 0.0.0.0 0.0.0.0 198.51.100.1');
const natR1 = s('PAT LAN / ISP1', 'Cho mạng LAN ra WAN1.', 'access-list 1 permit 10.10.10.0 0.0.0.255\ninterface {{LAN_PORT}}\n ip nat inside\nexit\ninterface {{WAN_PORT}}\n ip nat outside\nexit\nip nat inside source list 1 interface {{WAN_PORT}} overload');
const natR2 = s('PAT LAN / ISP2', 'Cho mạng LAN ra WAN2.', 'access-list 1 permit 10.10.10.0 0.0.0.255\ninterface {{LAN_PORT}}\n ip nat inside\nexit\ninterface {{WAN_PORT}}\n ip nat outside\nexit\nip nat inside source list 1 interface {{WAN_PORT}} overload');
const twoTrunks = (first: string, second: string) => s('Trunk uplinks', 'Hai liên kết vật lý khác nhau; thay port theo model.', `interface {{TRUNK_PORT_1}}\n description TO_${first}\n switchport mode trunk\n switchport trunk allowed vlan 10,20\n no shutdown\nexit\ninterface {{TRUNK_PORT_2}}\n description TO_${second}\n switchport mode trunk\n switchport trunk allowed vlan 10,20\n no shutdown\nexit`);
const ssh = s('SSH', 'Thay secret mẫu và bảo đảm thiết bị có IP quản trị trước khi truy cập từ xa.', 'ip domain-name lab.local\nusername {{ADMIN_USER}} privilege 15 secret {{ADMIN_SECRET}}\ncrypto key generate rsa modulus 2048\nip ssh version 2\nline vty 0 4\n login local\n transport input ssh\nexit');
const portSec = s('Port Security', 'Chỉ áp dụng cổng access nối endpoint.', 'interface {{ACCESS_PORT}}\n switchport mode access\n switchport access vlan 10\n switchport port-security\n switchport port-security maximum 2\n switchport port-security mac-address sticky\n switchport port-security violation restrict\n no shutdown\nexit');
const commonLab = ['VLAN10: 10.10.10.0/24, gateway 10.10.10.1', 'VLAN20: 10.10.20.0/24, gateway 10.10.20.1', 'Cổng theo cú pháp IOS có thể thay trong Generate Config.'];
function device(name: string, ...sections: LibrarySection[]): DeviceRecipe { return { name, sections: [starter(name), ...sections, save] }; }
function full(title: string, categoryTags: string[], topology: string, lab: string[], devices: DeviceRecipe[], verify: VerifyCommand[], issues: LibraryArticle['issues'], options: { caution?: string; variables?: Record<string, string>; description?: string; preparation?: LibrarySection[] } = {}) {
  const id = `full-${fulls.length + 1}`;
  const values: Record<string, string> = { ...defaults, ...options.variables };
  for (const entry of devices) values[hostnameKey(entry.name)] = entry.name;
  const parameterizeIPs = (value: string) => value.replace(/\b(?:\d{1,3}\.){3}\d{1,3}\b/g, ip => {
    if (ip === '0.0.0.0') return ip;
    const key = `IP_${ip.replace(/\./g, '_')}`;
    values[key] = ip;
    return `{{${key}}}`;
  });
  const templatedDevices = devices.map(entry => ({ ...entry, sections: entry.sections.map(section => ({ ...section, code: parameterizeIPs(section.code) })) }));
  fulls.push({ id, title, category: 'FULL CONFIG', kind: 'full', description: options.description || `Cấu hình hoàn chỉnh ${title.replace(/^Full /, '')}, kèm lệnh kiểm tra và xử lý lỗi.`, tags: ['Cisco', 'CCNA', 'Full Config', ...categoryTags], topology, lab: lab.map(parameterizeIPs), devices: templatedDevices, preparation: options.preparation, verify, issues, caution: options.caution, variables: values });
}
const switchTopology = 'PC VLAN10 ── Fa0/1-5 ──┐\n                         SW1 ── Gi0/1 trunk ── SW2 / Router\nPC VLAN20 ── Fa0/6-10 ─┘';
const routedTopology = 'PC VLAN10 ─┐\n            SW-L3 ── routed Gi0/2 ── R1 / ISP\nPC VLAN20 ─┘';
const hsrpTopology = 'ISP1 ── R1 ──┐\n               SW1 ── VLAN10 clients (VIP .1)\nISP2 ── R2 ──┘';
full('Full Switch Layer 2 cơ bản', ['Switch L2', 'VLAN'], switchTopology, [...commonLab, 'Management: VLAN99, Fa0/24, 192.0.2.2/24'], [device('SW1', l2Vlan, l2Access, l2Trunk, mgmt)], [...vlanVerify, v('show ip interface brief', 'Xem SVI quản trị.')], [vlanIssue], { caution: 'Reset gây mất cấu hình và gián đoạn. Sao lưu, xác nhận từng lệnh; chỉ áp dụng trước cấu hình mới.', preparation: [s('Reset (tùy chọn)', 'Chạy thủ công từng lệnh; xóa vlan.dat chỉ khi tệp tồn tại trên switch.', 'enable\nwrite erase\ndelete flash:vlan.dat\nreload')] });
full('Full Switch L2 + VLAN + Access + Trunk', ['Switch L2', 'VLAN', 'Trunk'], switchTopology, commonLab, [device('SW1', l2Vlan, l2Access, l2Trunk)], vlanVerify, [vlanIssue]);
full('Full Switch L2 + STP + Rapid-PVST', ['Switch L2', 'STP'], switchTopology, commonLab, [device('SW1', l2Vlan, l2Access, l2Trunk, l2Stp)], [...vlanVerify, v('show spanning-tree vlan 10', 'Xem root và port role.')], [issue('Switch không thành root', 'Kiểm tra bridge priority trên các switch.', 'Kiểm tra trunk đang cho VLAN 10 đi qua.')]);
full('Full Switch L2 + LACP', ['Switch L2', 'LACP'], 'SW1 Gi0/1-2 ══ Port-channel1 ══ SW2 Gi0/1-2', commonLab, [device('SW1', l2Vlan, l2Access, l2Lacp), device('SW2', l2Vlan, l2LacpPeer)], lacpVerify, [lacpIssue]);
full('Full Switch L2 + VLAN + Trunk + STP + LACP', ['Switch L2', 'VLAN', 'Trunk', 'STP', 'LACP'], 'PCs ── SW1 ══ Po1/LACP ══ SW2', commonLab, [device('SW1', l2Vlan, l2Access, l2Lacp, l2Stp), device('SW2', l2Vlan, l2LacpPeer, s('STP Secondary', 'SW2 dự phòng root.', 'spanning-tree mode rapid-pvst\nspanning-tree vlan 10,20 root secondary'))], [...vlanVerify, ...lacpVerify, v('show spanning-tree', 'Xem root và port role.')], [vlanIssue, lacpIssue]);
full('Full Switch Layer 3', ['Switch L3', 'SVI'], routedTopology, [...commonLab, 'SW-L3 Gi0/2: 192.0.2.2/30; R1: 192.0.2.1'], [device('SW-L3', l3Svi, l2Access, l3Uplink)], routeVerify, [issue('Không liên VLAN', 'Xác nhận ip routing và SVI up/up.', 'Access port phải thuộc VLAN đúng.')]);
full('Full L3 Switch Inter-VLAN Routing', ['Switch L3', 'Inter-VLAN'], routedTopology, commonLab, [device('SW-L3', l3Svi, l2Access)], [...routeVerify, ...vlanVerify], [vlanIssue]);
full('Full L3 Switch + DHCP', ['Switch L3', 'DHCP'], routedTopology, commonLab, [device('SW-L3', l3Svi, l2Access, dhcp10)], [...routeVerify, v('show ip dhcp binding', 'Xem lease được cấp.')], [vlanIssue]);
full('Full Router-on-a-Stick', ['Router', 'VLAN', 'Trunk'], 'R1 Gi0/1 ── trunk ── SW1 ── VLAN10 / VLAN20', commonLab, [device('R1', ros), device('SW1', l2Vlan, l2Access, l2Trunk)], [...routeVerify, ...vlanVerify], [vlanIssue], { variables: { TRUNK_PORT: 'GigabitEthernet0/1', REMOTE_DEVICE: 'R1' } });
full('Full Router Cisco cấp DHCP', ['Router', 'DHCP'], 'ISP ── R1 ── LAN 10.10.10.0/24 ── PC', ['R1 LAN: 10.10.10.1/24', 'DHCP: 10.10.10.21–254'], [device('R1', routerLan, dhcp10)], [v('show ip dhcp binding', 'Xem lease.'), ...routeVerify], [issue('PC không nhận IP', 'Kiểm tra LAN interface up/up.', 'Kiểm tra DHCP pool và excluded-address.')]);
full('Full Static Route', ['Router', 'Routing'], 'LAN10 ── R1 ── 192.0.2.0/30 ── R2 ── LAN20', ['R1 LAN: 10.10.10.1/24', 'R2 LAN: 10.10.20.1/24', 'R1 WAN: 192.0.2.1/30; R2 WAN: 192.0.2.2/30'], [device('R1', routerLan, s('WAN / Static Route', 'Tuyến tới LAN20 qua R2.', 'interface {{WAN_PORT}}\n ip address 192.0.2.1 255.255.255.252\n no shutdown\nexit\nip route 10.10.20.0 255.255.255.0 192.0.2.2')), device('R2', s('LAN', 'Gateway LAN20.', 'interface {{LAN_PORT}}\n ip address 10.10.20.1 255.255.255.0\n no shutdown\nexit'), s('WAN / Static Route', 'Tuyến quay về LAN10.', 'interface {{WAN_PORT}}\n ip address 192.0.2.2 255.255.255.252\n no shutdown\nexit\nip route 10.10.10.0 255.255.255.0 192.0.2.1'))], routeVerify, [issue('Ping một chiều', 'Phải có route chiều về trên R2.', 'Kiểm tra interface WAN up/up.')]);
full('Full OSPF', ['Router', 'OSPF'], 'LAN10 ── R1 ── 192.0.2.0/30 ── R2 ── LAN20', ['R1 LAN: 10.10.10.0/24', 'R2 LAN: 10.10.20.0/24', 'WAN: 192.0.2.0/30, area 0'], [device('R1', routerLan, s('WAN', 'R1 của liên kết OSPF.', 'interface {{WAN_PORT}}\n ip address 192.0.2.1 255.255.255.252\n no shutdown\nexit'), ospf), device('R2', s('LAN / WAN', 'Đặt IP cho hai cổng R2.', 'interface {{LAN_PORT}}\n ip address 10.10.20.1 255.255.255.0\n no shutdown\nexit\ninterface {{WAN_PORT}}\n ip address 192.0.2.2 255.255.255.252\n no shutdown\nexit'), s('OSPF', 'Quảng bá LAN20 và mạng chung.', 'router ospf 1\n router-id 2.2.2.2\n network 10.10.20.0 0.0.0.255 area 0\n network 192.0.2.0 0.0.0.3 area 0\nexit'))], [v('show ip ospf neighbor', 'Xem adjacency FULL.'), ...routeVerify], [issue('Không hình thành neighbor', 'Kiểm tra area, IP/mask và trạng thái interface.', 'Kiểm tra ACL có chặn OSPF.')]);
full('Full NAT/PAT', ['Router', 'NAT', 'PAT'], 'LAN10 ── R1 (PAT) ── ISP', ['LAN: 10.10.10.0/24', 'R1 WAN: 192.0.2.2/30; ISP: 192.0.2.1'], [device('R1', routerLan, routerWan, nat)], [v('show ip nat translations', 'Xem bản dịch sau khi phát sinh lưu lượng.'), ...routeVerify], [issue('Không có NAT translation', 'Kiểm tra inside/outside và ACL 1.', 'Kiểm tra default route và kết nối ISP.')]);
full('Full PPPoE', ['Router', 'PPPoE'], 'LAN ── R1 Dialer1 ── PPPoE ISP', ['LAN: 10.10.10.0/24', 'PPPoE: nhập user/password ISP'], [device('R1', routerLan, s('PPPoE', 'Thông số xác thực theo ISP; CHAP là ví dụ.', 'interface {{WAN_PORT}}\n no ip address\n pppoe enable group global\n pppoe-client dial-pool-number 1\n no shutdown\nexit\ninterface Dialer1\n ip address negotiated\n encapsulation ppp\n dialer pool 1\n ppp chap hostname {{PPPOE_USER}}\n ppp chap password {{PPPOE_PASSWORD}}\nexit\nip route 0.0.0.0 0.0.0.0 Dialer1'))], [v('show pppoe session', 'Xem phiên PPPoE.'), ...routeVerify], [issue('Dialer không lên', 'Kiểm tra kết nối ISP và credential.', 'Đối chiếu CHAP/PAP, VLAN và MTU do ISP yêu cầu.')], { caution: 'Thay thông tin ISP; cú pháp và yêu cầu PPPoE tùy IOS và nhà cung cấp.' });
full('Full HSRP 2 Router', ['Router', 'HSRP'], hsrpTopology, ['VIP: 10.10.10.1/24', 'R1 LAN .2, priority 110; R2 LAN .3, priority 100', 'R1 ISP1: 192.0.2.0/30; R2 ISP2: 198.51.100.0/30'], [device('R1', hsrpR1, wan1, natR1), device('R2', hsrpR2, wan2, natR2)], [...hsrpVerify, v('show ip nat translations', 'Xem bản dịch PAT.')], [hsrpIssue]);
full('Full HSRP + Track WAN', ['Router', 'HSRP', 'Track', 'Failover'], hsrpTopology, ['VIP: 10.10.10.1/24', 'R1 priority 110 → 80 nếu WAN down; R2 priority 100', 'R1 ISP1: 192.0.2.0/30; R2 ISP2: 198.51.100.0/30'], [device('R1', hsrpR1, wan1, natR1, trackWan), device('R2', hsrpR2, wan2, natR2)], [...hsrpVerify, v('show ip nat translations', 'Kiểm tra PAT trên router Active.'), ...routeVerify], [hsrpIssue], { caution: 'Track interface chỉ phát hiện link down; dùng IP SLA nếu lỗi nằm xa hơn cổng WAN.' });
full('Full Dual Router WAN Failover', ['Router', 'HSRP', 'Failover'], hsrpTopology, ['VIP: 10.10.10.1/24', 'ISP1 next hop 192.0.2.1; ISP2 next hop 198.51.100.1'], [device('R1', hsrpR1, wan1, natR1, trackWan), device('R2', hsrpR2, wan2, natR2)], [...hsrpVerify, v('show ip nat translations', 'Kiểm tra PAT trên router Active.'), ...routeVerify], [hsrpIssue]);
const fourVlanLab = [10,20,30,40].map(id => `VLAN${id}: 10.10.${id}.0/24, VIP 10.10.${id}.1; R1 .2, R2 .3`);
function hsrpFour(router: 'R1'|'R2') { return s('HSRP 4 VLAN', `${router}: Active cho ${router === 'R1' ? '10,30' : '20,40'}.`, 'interface {{TRUNK_PORT}}\n no ip address\n no shutdown\nexit\n' + [10,20,30,40].map(id => `interface {{TRUNK_PORT}}.${id}\n encapsulation dot1Q ${id}\n ip address 10.10.${id}.${router === 'R1' ? 2 : 3} 255.255.255.0\n standby ${id} ip 10.10.${id}.1\n standby ${id} priority ${((id === 10 || id === 30) === (router === 'R1')) ? 110 : 100}\n standby ${id} preempt\nexit`).join('\n')); }
const fourVlanSwitch = s('VLAN / Trunk', 'Tạo 4 VLAN; mỗi cổng nối router là trunk.', 'vlan 10\nexit\nvlan 20\nexit\nvlan 30\nexit\nvlan 40\nexit\ninterface {{TRUNK_PORT_1}}\n switchport mode trunk\n switchport trunk allowed vlan 10,20,30,40\n no shutdown\nexit\ninterface {{TRUNK_PORT_2}}\n switchport mode trunk\n switchport trunk allowed vlan 10,20,30,40\n no shutdown\nexit');
const fourVlanAccess = s('Access Port', 'Mỗi cổng PC vào một VLAN.', [10,20,30,40].map(id => `interface {{ACCESS_PORT_${id}}}\n switchport mode access\n switchport access vlan ${id}\n spanning-tree portfast\n spanning-tree bpduguard enable\n no shutdown\nexit`).join('\n'));
full('Full 4 VLAN + 2 Router HSRP', ['Router', 'HSRP', 'VLAN'], 'R1 ─┐\n    SW1 trunk ── VLAN10/20/30/40\nR2 ─┘', [...fourVlanLab, 'SW1 Fa0/1-4 lần lượt thuộc VLAN10/20/30/40'], [device('R1', hsrpFour('R1')), device('R2', hsrpFour('R2')), device('SW1', fourVlanSwitch, fourVlanAccess)], [...hsrpVerify, ...vlanVerify], [hsrpIssue, vlanIssue]);
full('Full Router + L3 + L2', ['Router', 'Switch L3', 'Switch L2'], 'ISP ── R1 ── routed ── SW-L3 ── trunk ── SW-L2 ── PCs', [...commonLab, 'R1↔L3: 192.0.2.0/30', 'R1↔ISP: 198.51.100.0/30'], [device('R1', s('Uplink / Routes', 'R1 nối SW-L3.', 'interface {{LAN_PORT}}\n ip address 192.0.2.1 255.255.255.252\n ip nat inside\n no shutdown\nexit\nip route 10.10.10.0 255.255.255.0 192.0.2.2\nip route 10.10.20.0 255.255.255.0 192.0.2.2'), routerWan198, s('PAT', 'Dịch hai mạng VLAN ra ISP.', 'access-list 1 permit 10.10.10.0 0.0.0.255\naccess-list 1 permit 10.10.20.0 0.0.0.255\ninterface {{WAN_PORT}}\n ip nat outside\nexit\nip nat inside source list 1 interface {{WAN_PORT}} overload')), device('SW-L3', l3Svi, l3Uplink, l2Trunk), device('SW-L2', l2Vlan, l2Access, l2Trunk)], [...routeVerify, ...vlanVerify, v('show ip nat translations', 'Xem PAT sau khi có lưu lượng.')], [vlanIssue], { variables: { REMOTE_DEVICE: 'SW-L3' } });
full('Full Router + nhiều Switch L2', ['Router', 'Switch L2', 'VLAN'], 'R1 ── trunk ── SW1 ── trunk ── SW2 ── PCs', commonLab, [device('R1', ros), device('SW1', l2Vlan, l2Access, twoTrunks('R1', 'SW2')), device('SW2', l2Vlan, l2Access, s('Trunk to SW1', 'Gi0/1 nối SW1 Gi0/2.', 'interface GigabitEthernet0/1\n switchport mode trunk\n switchport trunk allowed vlan 10,20\n no shutdown\nexit'))], [...routeVerify, ...vlanVerify], [vlanIssue]);
full('Full LACP giữa 2 Switch', ['Switch L2', 'LACP'], 'SW1 Gi0/1-2 ══ Po1 ══ SW2 Gi0/1-2', commonLab, [device('SW1', l2Vlan, l2Lacp), device('SW2', l2Vlan, l2LacpPeer)], lacpVerify, [lacpIssue]);
full('Full STP mô hình nhiều Switch', ['Switch L2', 'STP', 'Rapid-PVST'], 'SW1 Gi0/1 ── Gi0/1 SW2\n Gi0/2 ╲      ╱ Gi0/2\n        SW3 Gi0/1-2', [...commonLab, 'Mỗi switch dùng Gi0/1 và Gi0/2 làm trunk'], [device('SW1', l2Vlan, l2Stp, twoTrunks('SW2', 'SW3')), device('SW2', l2Vlan, s('STP Secondary', 'Dự phòng root khi SW1 mất.', 'spanning-tree mode rapid-pvst\nspanning-tree vlan 10,20 root secondary'), twoTrunks('SW1', 'SW3')), device('SW3', l2Vlan, s('STP', 'Switch edge tham gia Rapid-PVST.', 'spanning-tree mode rapid-pvst'), twoTrunks('SW1', 'SW2'))], [...vlanVerify, v('show spanning-tree vlan 10', 'Xem root và cổng blocking.')], [issue('Loop hoặc root sai', 'Kiểm tra tất cả liên kết giữa switch.', 'So sánh bridge ID và priority trên từng thiết bị.')]);
full('Full cấu hình SSH quản trị thiết bị', ['Security', 'SSH'], 'Admin PC ── MGMT VLAN99 ── SW1', ['SW1 SVI VLAN99: 192.0.2.2/24', 'Management port: Fa0/24', 'Default gateway: 192.0.2.1', 'Đổi username và secret trước khi dùng'], [device('SW1', mgmt, ssh)], [v('show ip ssh', 'Xem SSHv2.'), v('show ip interface brief', 'Xem SVI quản trị.')], [issue('SSH timeout', 'Kiểm tra VLAN quản trị, SVI và gateway.', 'Kiểm tra RSA key, VTY và ACL.')], { caution: 'Đổi secret mẫu trước khi áp dụng.' });
full('Full Port Security', ['Switch L2', 'Security'], 'PC ── Fa0/1 ── SW1', ['VLAN10: 10.10.10.0/24', 'Access port: Fa0/1', 'Giới hạn tối đa 2 MAC'], [device('SW1', l2Vlan, portSec)], [v('show port-security interface {{ACCESS_PORT}}', 'Xem MAC và vi phạm.'), ...vlanVerify], [issue('Port bị chặn', 'Kiểm tra MAC đã học và mức maximum.', 'Kiểm tra violation mode.')]);
full('Full cấu hình Cisco từ RESET → HOÀN CHỈNH', ['Switch L2', 'Reset', 'SSH'], switchTopology, [...commonLab, 'Reset thực hiện thủ công trước khi áp dụng cấu hình mới.', 'Management: VLAN99, Fa0/24, 192.0.2.2/24'], [device('SW1', l2Vlan, l2Access, l2Trunk, mgmt, ssh)], [...vlanVerify, v('show ip ssh', 'Xem SSH.')], [vlanIssue], { caution: 'Reset gây mất cấu hình và gián đoạn; thao tác riêng sau khi sao lưu. Thay SSH secret mẫu trước khi áp dụng Full Config.', preparation: [s('Reset', 'Chạy thủ công từng lệnh, xác nhận prompt; bỏ qua vlan.dat nếu thiết bị không có tệp.', 'enable\nwrite erase\ndelete flash:vlan.dat\nreload')] });

export const fullArticles = fulls;
export const ciscoLibrary: LibraryArticle[] = [...fulls, ...topics];
export const getLibraryArticle = (id: string) => ciscoLibrary.find(article => article.id === id);
export function articleInCategory(article: LibraryArticle, category: string): boolean {
  if (category === 'SWITCHING') return article.kind === 'topic' && article.tags.some(tag => ['VLAN', 'Trunk', 'STP', 'Rapid-PVST', 'LACP', 'EtherChannel'].includes(tag));
  if (category === 'SECURITY') return article.kind === 'topic' && (article.category === category || article.tags.includes('Security'));
  if (category === 'ROUTING') return article.kind === 'topic' && (article.category === category || article.tags.includes('Routing') || article.tags.includes('OSPF'));
  if (category === 'ROUTER CISCO') return article.category === category || (article.kind === 'topic' && (article.tags.includes('Routing') || article.tags.includes('OSPF') || article.tags.includes('ACL') || article.tags.includes('HSRP')));
  return article.category === category;
}
export function matchesLibraryArticle(article: LibraryArticle, query: string): boolean {
  const normalize = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/đ/g, 'd').toLowerCase();
  const words = normalize(query).split(/\s+/).filter(Boolean);
  if (!words.length) return true;
  const content = normalize([article.title, article.category, article.description, ...article.tags, article.topology || '', ...(article.lab || []), ...Object.values(article.variables || {}), ...article.devices.flatMap(device => [device.name, ...device.sections.flatMap(section => [section.title, section.explanation, section.code])]), ...article.verify.flatMap(item => [item.command, item.meaning])].join(' '));
  return words.every(word => content.includes(word));
}
export function renderTemplate(text: string, values: Record<string, string>): string {
  return text.replace(/{{([A-Z0-9_]+)}}/g, (match, key: string) => values[key]?.trim() || match);
}
export function templateKeys(article: LibraryArticle): string[] {
  const text = article.devices.flatMap(device => device.sections.map(section => section.code)).join('\n');
  return Array.from(text.matchAll(/{{([A-Z0-9_]+)}}/g), match => match[1]).filter((key, index, all) => all.indexOf(key) === index);
}
export function deviceConfig(device: DeviceRecipe, values: Record<string, string>): string {
  return device.sections.map(section => renderTemplate(section.code, values)).join('\n\n');
}
